* Obsah :toc:
- [[#proč-jsem-vytvořil-tento-repositář][Proč jsem vytvořil tento repositář?]]
- [[#instalace-emacs][Instalace Emacs]]
- [[#instalace-doom-emacs][Instalace Doom Emacs]]
- [[#první-spuštění-doom-emacs][První spuštění Doom Emacs]]

* Proč jsem vytvořil tento repositář?
Protože si myslím, že v CZ není dost up-to-date návodů pro instalaci a základní zacházení s Doom Emacs. Proto vás provedu instalací a základními nástroji v Doom Emacs. Tak pojďme na to.

* Instalace Emacs
 Instalace samotného Emacs je velice jednoduchá. Stačí napsat do terminálu příkaz pro instalaci emacs.
    Příklady
        Ubuntu a Ubuntu based distra
        "sudo apt-get install emacs"

        Fedora
        "sudo dnf install emacs"

        Arch a Arch based distra
        "sudo pacman install emacs" nebo "yay install emacs"

        OpenSuse
        "sudo zypper install emacs"

        MacOS
            Homebrew:
        "brew install --cask emacs"
                nebo
            MacPorts
        "sudo port install emacs-app"

* Instalace Doom Emacs
    Instalace Doom Emacs je velice jednoduchá. V první řadě si zálohujeme naši konfiguraci emacs příkazem
    "mv/home/vaseusername/.emacs.d /home/vaseusername/.emacs.d.backup"

    Po té můžeme clonovat repositář do složky .emacs.d, to můžeme udělat pomocí příkazu "git clone --depth 1 https://github.com/hlissner/doom-emacs /home/vaseusername/.emacs.d". Po dokončení příkazu můžeme spustit instalaci Doom Emacs pomocí příkazu "/home/vaseusername/.emacs.d/bin/doom install" Při instalaci budete dotázání na 2 otázky, na obě odpovězte Y.

* První spuštění Doom Emacs
    Pří prvním spuštění Doom Emacs uvidíte hlavní obrazovku s několika možnostmi
