* Obsah :toc:
- [[#instalace-emacs][Instalace Emacs]]
- [[#instalace-doom-emacs][Instalace Doom Emacs]]
- [[#gratulace][Gratulace!]]

* Instalace Emacs
 Instalace samotného Emacs je velice jednoduchá. Stačí napsat do terminálu příkaz pro instalaci emacs.
    Příklady
        Ubuntu a Ubuntu based distra
        "sudo apt-get install emacs"

        Fedora
        "sudo dnf install emacs"

        Arch a Arch based distra
        "sudo pacman install emacs" nebo "yay install emacs"

        OpenSuse
        "sudo zypper install emacs"

        MacOS
            Homebrew:
        "brew install --cask emacs"
                nebo
            MacPorts
        "sudo port install emacs-app"

* Instalace Doom Emacs
    Instalace Doom Emacs je velice jednoduchá. V první řadě si zálohujeme naši konfiguraci emacs příkazem
    "mv/home/vaseusername/.emacs.d /home/vaseusername/.emacs.d.backup"

    Po té můžeme clonovat repositář do složky .emacs.d, to můžeme udělat pomocí příkazu "git clone --depth 1 https://github.com/hlissner/doom-emacs /home/vaseusername/.emacs.d". Po dokončení příkazu můžeme spustit instalaci Doom Emacs pomocí příkazu "/home/vaseusername/.emacs.d/bin/doom install" Při instalaci budete dotázání na 2 otázky, na obě odpovězte Y.

* Gratulace!
    Gratuluji, právě jsi nainstaloval Doom Emacs na svojí linuxovou distribuci! Doporučuji se ti podívat na další kroky, budou zde v repositáři taky. Díky za přečtení!


    --Smajl
